name: Build and Package Artifacts

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        java-version: ['11', '17', '21']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: gowridurgad/setup-java-fork@testing-snap
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'sapmachine'
      - name: Build with Maven
        run: mvn clean package
      - name: Package artifacts
        run: tar -czvf my-artifacts-${{ matrix.os }}-${{ matrix.java-version }}.tar.gz target/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts-${{ matrix.os }}-${{ matrix.java-version }}
          path: my-artifacts-${{ matrix.os }}-${{ matrix.java-version }}.tar.gz
