name: build artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
        java-version: ['11', '17', '21']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: gowridurgad/setup-java-fork@testing-snap
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'sapmachine'
      - name: Build with Maven
        run: mvn clean package
      - name: Package artifacts
        run: |
          if [ ${{ runner.os }} == 'Windows' ]; then
            Compress-Archive -Path target\* -DestinationPath my-artifacts-${{ matrix.java-version }}.zip
          else
            tar -czvf my-artifacts-${{ matrix.java-version }}.tar.gz target/
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts-${{ matrix.java-version }}
          path: |
            my-artifacts-${{ matrix.java-version }}.tar.gz
            my-artifacts-${{ matrix.java-version }}.zip
