name: build artifacts

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: ['11', '21', '17', '22']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: gowridurgad/setup-java-fork@testing-snap
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'sapmachine'
      - name: Build with Maven
        run: mvn clean package
      - name: Package artifacts
        run: |
          zip -r sapmachine-jdk-${{ matrix.java-version }}_windows-x64_bin.zip target/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sapmachine-jdk-${{ matrix.java-version }}_windows-x64_bin
          path: sapmachine-jdk-${{ matrix.java-version }}_windows-x64_bin.zip
