name: build artifacts

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'dragonwell'
      - name: Build with Maven
        run: mvn clean package
      - name: Package artifacts
        run: tar -czvf my-artifacts-${{ matrix.java-version }}.tar.gz target/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts-${{ matrix.java-version }}
          path: my-artifacts-${{ matrix.java-version }}.tar.gz
