name: cachewithsbt 

on:
   workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        java-version: [11, 17, 21 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
           distribution: 'dragonwell'
           java-version: ${{ matrix.java-version }}
           cache: 'sbt'
           cache-dependency-path: build.sbt            
      - name: Build with SBT
        run: sbt package
