name: cachewithgradle

on:
   workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [11, 17, 21 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
           distribution: 'sapmachine'
           java-version: ${{ matrix.java-version }}
           cache: 'gradle'
      - run: ./gradlew build --no-daemon
         
