name: cachewithsbt

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      
      - uses: gowridurgad/setup-java-fork@testing-snap
        with:
          distribution: 'sapmachine'
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'

      - name: Cache SBT packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', '**/build.properties', '**/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Build with SBT
        run: sbt package
