name: cachewithsbt 

on:
   workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-java-fork@testing-snap
        with:
           distribution: 'sapmachine'
           java-version: '21'
           cache: 'sbt'
           cache-dependency-path: | # optional
               build.sbt
               build.properties
      - name: Build with SBT
        run: sbt package
