name: cachewithsbt

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        java-version: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      
      - uses: gowridurgad/setup-java-fork@testing-snap
        with:
          distribution: 'sapmachine'
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
          

      - name: Install SBT
        run: |
          curl -L -o sbt.tgz https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.tgz
          tar -xzf sbt.tgz
          sudo mv sbt /usr/local/sbt
          echo 'export PATH=$PATH:/usr/local/sbt/bin' >> $GITHUB_ENV

      - name: Build with SBT
        run: sbt package
