name: Check-latest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['11', '17', '21']
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java-version }}
        uses: gowridurgad/jjava-setup-fork@testing-snap
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'sapmachine' 
          check-latest: true
      - name: Verify Java version
        run: java -version
