name: gpgmaven

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: gowridurgad/setup-java-fork@testing-snap
        with:
          distribution: 'sapmachine'
          java-version: ${{ matrix.java-version }}

      - name: Set up GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$GPG_PASSPHRASE" | gpg --batch --passphrase-fd 0 --pinentry-mode loopback --edit-key <KEY_ID> trust quit
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages
        run: mvn deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
