name: gradletesting

on:
   workflow_dispatch

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [11, 17, 21 ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: gowridurgad/setup-java-fork@testing-snap
      with:
        distribution: 'sapmachine'
        java-version: ${{ matrix.java-version }}

    - name: Build with Gradle
      run: gradle build

    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
