
name: issuezip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    

    - name: Setup python
      uses: priyagupta108/setup-python@fix-windows-extract-archive
      with:
          python-version: '3.6.x - 3.11.x'

   
