name: issue519

on:
   workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
           distribution: 'adopt'
           java-version: ${{ matrix.java-version }}
           check-latest: true
           cache: 'gradle'
           
      - run: ./gradlew build --no-daemon
