name: issue519

on: 
    workflow_dispatch:

jobs:
  setup-java:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
   
      - name: Check cached Java versions
        run: |
           echo "JAVA_HOME_8_X64: $JAVA_HOME_8_X64"
           echo "JAVA_HOME_11_X64: $JAVA_HOME_11_X64"
           echo "JAVA_HOME_17_X64: $JAVA_HOME_17_X64"
           echo "JAVA_HOME_21_X64: $JAVA_HOME_21_X64"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
          check-latest: false
