name: mavenpublish

on:
   workflow_dispatch

jobs:

  build:
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [11, 17, 21 ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: gowridurgad/setup-java-fork@testing-snap
      with:
        distribution: 'sapmachine'
        java-version: ${{ matrix.java-version }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  
