name: mavenpublish

on:
   workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: gowridurgad/setup-java-fork@testing-snap
      with:
        distribution: 'sapmachine'
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  
