name: patchversions

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        java-version: ['11', '17', '21','22', '21.0.4', '17.0.12', '11.0.24', '22.0.2']
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-java-fork@testing-snap
        with:
          distribution: 'sapmachine'
          java-version: ${{ matrix.java-version }}
 
