name: patchversions

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        java-version: ['11']
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-java-fork@testing-snap
        with:
          distribution: 'sapmachine'
          java-version: ${{ matrix.java-version }}
 
