name: Publish Maven package to GPR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        java-version: [17]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Apache Maven Central
      uses: gowridurgad/setup-java-fork@testing-snap
      with:
        distribution: 'sapmachine'
        java-version: ${{ matrix.java-version }}
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.MY_GPG_PASSPHRASE }}  # Set the passphrase correctly here

    - name: Set up GPG Passphrase
      run: echo "MY_GPG_PASSPHRASE=${{ secrets.MY_GPG_PASSPHRASE }}" >> $GITHUB_ENV


    - name: Publish to Apache Maven Central
      run: mvn -P release --batch-mode deploy -DskipTests -Dgpg.passphrase=$MY_GPG_PASSPHRASE
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
